### ISSUE TITLE
Build error: Can't import the named export 'Children' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by jaymzh** [fkhadra/react-contexify#254]
First, thanks for this project, it looks like exactly what I need!

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I can't build, when I try I get:

```javascript
./node_modules/react-contexify/dist/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

**What is the expected behavior?**

It builds

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

MacOS, react 17.0.2, react-contextify 6.0.0.

No browser since I can't even build yet. :)

**Comment by jaymzh** [comment]
Oh I just realized this is probably related to the errors from yarn add, copied below. I'm temporarily on a mac dev system which I'm not used to. Once I get back to my linux dev system this will probably get sorted out. But in case anyone is curious here were the build errors:

```
warning Error running install script for optional dependency: "/Users/phil/src/ipom/picks-app/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/phil/src/ipom/picks-app/node_modules/fsevents
Output:
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}

Node.js v20.5.1"
[-/2] ⠐ waiting...
warning Error running install script for optional dependency: "/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@20.5.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v115-darwin-x64.tar.gz
node-pre-gyp http 403 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v115-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v115-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@20.5.1 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 403 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v115-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.5.1 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.5.1 | darwin | x64
gyp info find Python using Python version 3.11.5 found at \"/usr/local/opt/python@3.11/bin/python3.11\"
gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/phil/src/ipom/picks-app/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/phil/src/ipom/picks-app/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/phil/Library/Caches/node-gyp/20.5.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/phil/src/ipom/picks-app/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/phil/Library/Caches/node-gyp/20.5.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.4.0
gyp info using node@20.5.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../../../nan/nan.h:686:39: warning: 'IdleNotificationDeadline' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
    return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
                                      ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-isolate.h:1291:3: note: 'IdleNotificationDeadline' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8config.h:550:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
../fsevents.cc:50:32: error: no template named 'Handle' in namespace 'v8'
    static void Initialize(v8::Handle<v8::Object> exports);
                           ~~~~^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder-ctor]
   : async_resource(\"fsevents:FSEvents\"), lockStarted(false) {
     ^
In file included from ../fsevents.cc:82:
../src/constants.cc:89:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagNone\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagNone));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:90:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagMustScanSubDirs\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMustScanSubDirs));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:91:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagUserDropped\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUserDropped));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:92:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagKernelDropped\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagKernelDropped));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:93:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagEventIdsWrapped\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagEventIdsWrapped));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:94:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagHistoryDone\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagHistoryDone));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:95:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagRootChanged\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagRootChanged));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:96:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagMount\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMount));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:97:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagUnmount\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUnmount));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:98:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemCreated\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemCreated));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:99:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemRemoved\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRemoved));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:100:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemInodeMetaMod\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemInodeMetaMod));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:101:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemRenamed\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRenamed));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:102:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemModified\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemModified));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:103:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemFinderInfoMod\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemFinderInfoMod));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:104:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemChangeOwner\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemChangeOwner));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:105:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemXattrMod\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemXattrMod));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../fsevents.cc:82:
../src/constants.cc:106:11: error: no matching member function for call to 'Set'
  object->Set(Nan::New<v8::String>(\"kFSEventStreamEventFlagItemIsFile\").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemIsFile));
  ~~~~~~~~^~~
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:244:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/phil/Library/Caches/node-gyp/20.5.1/include/node/v8-object.h:247:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/phil/src/ipom/picks-app/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command \"/usr/local/Cellar/node/20.5.1/bin/node\" \"/Users/phil/src/ipom/picks-app/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64\" \"--napi_version=9\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents
gyp ERR! node -v v20.5.1
gyp ERR! node-gyp -v v9.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/20.5.1/bin/node /Users/phil/src/ipom/picks-app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64/fse.node --module_name=fse --module_path=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64 --napi_version=9 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/20.5.1/bin/node\" \"/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents
node-pre-gyp ERR! node -v v20.5.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/20.5.1/bin/node /Users/phil/src/ipom/picks-app/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64/fse.node --module_name=fse --module_path=/Users/phil/src/ipom/picks-app/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v115-darwin-x64 --napi_version=9 --node_abi_napi=napi' (1)"
```

**Comment by jaymzh** [comment]
Nope, even on my standard Linux setup when the package installed fine, it still doesn't work:

```
yarn run v1.22.19
$ dotenv -e .env.development react-app-rewired build
Creating an optimized production build...
Failed to compile.

./node_modules/react-contexify/dist/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

**Comment by jaymzh** [comment]
I found the solution from a similar problem people had over [here](https://github.com/framer/motion/issues/1525). Upgrading react-scripts solved it. Closing.
