### ISSUE TITLE
[v4-rc1]: Unexpected token export

### ISSUE THREAD

**Issue by joncursi** [fkhadra/react-contexify#86]
I get the following error when using v4 inside next.js:

```
/Users/joncursi/Sites/cheddur/web/node_modules/react-contexify/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { export { Menu } from './components/Menu';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:316:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/joncursi/Sites/cheddur/web/node_modules/@cheddur/core/lib/components/BottomSheet/index.js:14:23)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by fkhadra** [comment]
It is due to the fact that I don't transpile the import and export statement.
I'll push a new RC as soon as I get access to my  computer.
Thanks for reporting the issue.

**Comment by fkhadra** [comment]
Hey @joncursi,

I pushed a new rc. Are you using create-react-app or something else? Could you share your setup ?

Thanks.
